<?php
/**
 * @author Alan Barber <alan@cadence-labs.com>
 * Js template for newlsetter popup
 */
if (!$this->getConfig("enabled")) return;
?>
<script type="text/html" id="popup-template">
    <!-- Begin MailChimp Signup Form -->
    <div class="container-fluid mailchimp-popup-inner">
        <div class="row">
            <div class="left-col">
                <div class="">
                    <div id="mc_embed_signup">
                        <form action="<?php echo $this->getConfig("submit_url") ?>" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                            <div id="mc_embed_signup_scroll">

                                <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                                <div class="mc-field-group">
                                    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
                                    </label>
                                    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                                </div>
                                <div class="mc-field-group">
                                    <label for="mce-FNAME">First Name </label>
                                    <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
                                </div>
                                <div class="mc-field-group">
                                    <label for="mce-LNAME">Last Name </label>
                                    <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
                                </div>
                                <div id="mce-responses" class="clear">
                                    <div class="response" id="mce-error-response" style="display:none"></div>
                                    <div class="response" id="mce-success-response" style="display:none"></div>
                                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                <div style="position: absolute; left: -5000px;"><input type="text" name="<?php echo $this->getConfig("submit_key") ?>" tabindex="-1" value=""></div>
                                <div class="clear"><button type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button btn"><span><span>Subscribe</span></span></button></div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="right-col">
                <div class="col-xs-12">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cadence_mailchimp_callout')->toHtml() ?>
                </div>
            </div>
        </div>
    </div>
</script>
<script type="text/javascript">
    window.cadence_mailchimp = new Cadence.Mailchimp(<?php echo json_encode($this->getConfig()) ?>);
</script>